
import type { Metadata } from "next";
import { Inter, Indie_Flower, Roboto_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "./custom.css";
import Menu from '@/components/Menu';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ["latin"] });
const indieFlower = Indie_Flower({ weight: "400", subsets: ["latin"], variable: "--font-indie-flower" });
const robotoMono = Roboto_Mono({ subsets: ["latin"], variable: "--font-roboto-mono" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${indieFlower.variable} ${robotoMono.variable}`}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
